spring:
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8070
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/product
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    dialect: org.hibernate.dialect.PostgreSQLDialect
  #    database-platform: org.hibernate.dialect.PostgreSQL82Dialect

  application:
    name: order-service
