spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service
#  eureka:
#    instance:
#      hostname: localhost
#    client:
#      registererWithEureka: false
#      fetchRegistry: false
#      serviceUrl:
#        defaultZone: http://${eureka.instance.localhost}/${server.port}/eureka/
#
#  server:
#    port: 8761